server:
  port: 8088
spring:
  datasource:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host:        # Default to 'localhost' if not provided
    port:       # Default to 6379 if not provided
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
api:
  prefix: api/v1
jwt:
  expiration:
  secretKey:
aws:
  accessKey:
  secretKey:
  bucketName:
  folder:


#logging.level.org.springframework.security: DEBUG

logging:
  level:
    org:
      springframework.security: debug